# data: exp/dataset.de-en
# save_model: exp/model.de-en
data: /mkozuki/data/toy-ende
## Where the samples will be written
save_data: /mkozuki/data/toy-ende
## Where the vocab(s) will be written
src_vocab: /mkozuki/data/toy-ende/run/example.vocab.src
tgt_vocab: /mkozuki/data/toy-ende/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /mkozuki/data/toy-ende/src-train.txt
        path_tgt: /mkozuki/data/toy-ende/tgt-train.txt
    valid:
        path_src: /mkozuki/data/toy-ende/src-val.txt
        path_tgt: /mkozuki/data/toy-ende/tgt-val.txt

save_model: /mkozuki/data/opennmt_out_fusedadam
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 3435
train_steps: 20
valid_steps: 1000
warmup_steps: 8000
report_every: 5

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
hidden_size: 512
layers: 6
transformer_ff: 2048
heads: 8

model_dtype: "fp16"
accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
fused: 'true'

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0

